### ISSUE TITLE
warning+error after upgrading ciscopuppet to 1.6.0

### ISSUE THREAD

**Issue by VincentRitzer** [cisco/cisco-network-puppet-module#441]
After changing the ciscopuppet version to 1.6.0, it didn't automatically upgrade the cisco_node_utils.

Settings in our Puppetfile:
```puppet
-mod 'puppetlabs/ciscopuppet',     '1.5.0'
+mod 'puppetlabs/ciscopuppet',     '1.6.0'
```

Also we've included the automatic cisco_node_utils option:
```puppet
 include ciscopuppet::install.
```

Note: I've tested removing the cisco_node_utils gem and after it was removed it got installed again by running the puppet agent, so that part is working as intended.

output on commandline when running the puppet agent:
```
[root@n3k-1 guestshell]# puppet agent -t
Info: Using configured environment '2_production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Warning: This module works best with version 1.6.0 of gem 'cisco_node_utils' but version 1.5.0 is installed. Some features may not be fully functional.
Info: Caching catalog for 0dabe6a4-27c9-4b8e-824f-00fe626e8acf
Info: Applying configuration version '1490702950'
Error: Failed to apply catalog: undefined method `load_interval_counter_1_delay' for #<Cisco::Interface:0x000000034e2840>
[root@n3k guestshell]#
```

Please help.

**Comment by mikewiebe** [comment]
@VincentRitzer Can you include the contents of your `install.pp` manifest?  I want to make sure your `package` provider options have the correct properties set for upgrade.

**Comment by mikewiebe** [comment]
One more thing.  If you want to uninstall an old version, say `1.5.0` but leave any other versions installed create a manifest to remove version `1.5.0`.

```puppet
  package { 'cisco_node_utils' :
    ensure          => absent,
    provider        => 'gem',
    source          => $repo,
    uninstall_options => { '--version' => '1.5.0' }
  }
```

**Comment by VincentRitzer** [comment]
contents of the Puppetfile:
```puppet
class profile::nexus::ciscopuppet {
  include ::ciscopuppet::install
  include ::profile::nexus::netdev
```

The current gem list is:
```puppet
[root@DC1RT0001 guestshell]# gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
io-console (0.4.2)
json (1.7.7)
psych (2.0.0)
rdoc (4.0.0)
```

I will try to find out what happens when I add the option you mentioned to the puppetfile and will output the gem list then.

**Comment by tomcooperca** [comment]
@VincentRitzer use `/opt/puppetlabs/puppet/bin/gem list` to verify the installed gems. Likely, you're seeing the guestshell's "system" Ruby which is separate from the Puppet-included version of Ruby/gem.

For gem, you'll need to use an Exec. There's many posts on stackoverflow and the like where other people have run into this problem with the Gem provider on Linux.

We used the following:

```
$new_ver = '1.6.0'
$old_ver = '1.5.0'
package { 'cisco_node_utils' :
  ensure          => $new_ver,,
  provider        => puppet_gem,
  source          => $gem_source, # internal Gemserver
}
exec { "remove_cisco_node_utils_${old_ver}" :
  command => "/opt/puppetlabs/puppet/bin/gem uninstall cisco_node_utils -v=\'${old_ver}\'",
  onlyif  => "/opt/puppetlabs/puppet/bin/gem list -l cisco_node_utils | /bin/grep \'${old_ver}[,)]\'",
}
```
See here for more info: http://stackoverflow.com/questions/17763569/puppet-controlling-installed-package-version
